// Auto-generated by Bunnyx — do not edit
import { treaty } from '@elysiajs/eden';
import type { App } from '../src/index';

function getBaseUrl() {
  if (typeof window !== 'undefined') return window.location.origin;
  return 'http://localhost:3000';
}

export const api = treaty<App>(getBaseUrl());

export function createClient(baseUrl?: string) {
  return treaty<App>(baseUrl ?? getBaseUrl());
}
